[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
  "curl -fsSL 'https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64' -o /bin/pnpm; chmod +x /bin/pnpm;",
]

[build.env]
passthrough = [
  "GIT_TAG=TAG",
  "GIT_COMMIT=COMMIT"
]